force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>MV Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MV Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Plan__c/Product_Plan__c.object-meta.xml
<CustomObject>
    <label>Product Plan</label>
    <nameField>
        <label>Product Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Plan__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Plans</relationshipLabel>
    <relationshipName>Product_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Subscriber__c/Product_Subscriber__c.object-meta.xml
<CustomObject>
    <label>Product Subscriber</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Product Subscriber Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Subscriber__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Subscriber__c/fields/Expiration_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Expiration_DateTime__c</fullName>
    <label>Expiration DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product_Subscriber__c/fields/Is_Trial__c.field-meta.xml
<CustomField>
    <fullName>Is_Trial__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Trial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Subscriber__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Subscribers</relationshipLabel>
    <relationshipName>Product_Subscribers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Subscriber__c/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <label>Organization Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Subscriber__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Subscribers</relationshipLabel>
    <relationshipName>Product_Subscribers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Subscriber__c/fields/Product_Plan__c.field-meta.xml
<CustomField>
    <fullName>Product_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Plan</label>
    <referenceTo>Product_Plan__c</referenceTo>
    <relationshipLabel>Product Subscribers</relationshipLabel>
    <relationshipName>Product_Subscribers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Subscriber__c/fields/Product_Version__c.field-meta.xml
<CustomField>
    <fullName>Product_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Version</label>
    <referenceTo>Product_Version__c</referenceTo>
    <relationshipLabel>Product Subscribers</relationshipLabel>
    <relationshipName>Product_Subscribers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Subscriber__c/fields/Version_Number_Text__c.field-meta.xml
<CustomField>
    <fullName>Version_Number_Text__c</fullName>
    <label>Version Number (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Version__c/Product_Version__c.object-meta.xml
<CustomObject>
    <label>Product Version</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Version__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Versions</relationshipLabel>
    <relationshipName>Product_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductSubscriberManagementController.cls
public with sharing class ProductSubscriberManagementController {
    
    @AuraEnabled
    public static List<Product_Subscriber__c> getProductSubscribers(String productId) {
        return [SELECT Id, Name, Expiration_DateTime__c,Org_Name__c,Install_Date__c, Is_Trial__c, Product__r.Name, Product_Plan__r.Name ,Product_Version__r.Name , Discount__c, Duration__c, Version_Number_Text__c FROM Product_Subscriber__c WHERE Product__c = :productId ORDER BY LastModifiedDate DESC];
    }
    
    @AuraEnabled
    public static Product_Subscriber__c updateProductSubscriber(Id subscriberId, Boolean isTrial, Id productPlanId, Decimal discount, Integer duration, Datetime expirationDateTime) {
        try {
            Product_Subscriber__c subscriber = [SELECT Id, Is_Trial__c, Product_Plan__c, Discount__c, Duration__c, Price__c, Expiration_DateTime__c, Opportunity__c, Version_Number_Text__c FROM Product_Subscriber__c WHERE Id = :subscriberId];
            System.debug(' before update subscriber >>' + subscriber);
            
            subscriber.Is_Trial__c = isTrial;
            System.debug('isTrial >>' + isTrial);
            if (!isTrial) {
                subscriber.Product_Plan__c = productPlanId;
                subscriber.Discount__c = discount;
                subscriber.Duration__c = duration;
                subscriber.Expiration_DateTime__c = expirationDateTime;
                System.debug('productPlanId >>' + productPlanId);
                if (productPlanId != null) {
                    Product_Plan__c plan = [SELECT Price__c FROM Product_Plan__c WHERE Id = :productPlanId];
                    Decimal newPrice = plan.Price__c * duration;
                    subscriber.Price__c = newPrice;
                }
                if (expirationDateTime == null) {
                    List<Opportunity> oppRec = [SELECT Id, CloseDate FROM Opportunity WHERE Id = :subscriber.Opportunity__c];
                    if (!oppRec.isEmpty()) {
                        oppRec[0].CloseDate = Date.valueOf(expirationDateTime);
                        update oppRec[0];
                    }
                }
                System.debug('subscriber >>' + subscriber);
                
            }
            
            System.debug('after update subscriber >>' + subscriber);
            
            update subscriber;
            return subscriber;
        } catch (Exception e) {
            System.debug('Error retrieving product subscribers: ' + e.getMessage());
            throw new AuraHandledException('Error retrieving product subscribers: ' + e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Product_Plan__c> getProductPlans() {
        return [SELECT Id, Name, Price__c FROM Product_Plan__c];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Product__c> getProducts() {
        return [SELECT Id, Name FROM Product__c ORDER BY Name];
    }
}