force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>MV Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MV Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Version__c/Product_Version__c.object-meta.xml
<CustomObject>
    <label>Product Version</label>
    <nameField>
        <label>Product Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Version__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Versions</relationshipLabel>
    <relationshipName>Product_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Version__c/fields/Release_Notes__c.field-meta.xml
<CustomField>
    <fullName>Release_Notes__c</fullName>
    <label>Release Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Version__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beta</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Version__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <label>Version Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Version__c/fields/Version_URL__c.field-meta.xml
<CustomField>
    <fullName>Version_URL__c</fullName>
    <label>Version URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ProductVersionManagementController.cls
public with sharing class ProductVersionManagementController {
    public class ProductVersionResult {
        @AuraEnabled
        public List<Product_Version__c> versions {get;set;}
        @AuraEnabled
        public Integer totalRecords {get;set;}
    }

    @AuraEnabled(cacheable=true)
    public static List<Product__c> getProducts() {
        return [SELECT Id, Name FROM Product__c ORDER BY Name];
    }
    
    @AuraEnabled()
    public static ProductVersionResult getProductVersions(String productId) {
        ProductVersionResult result = new ProductVersionResult();
        result.versions = [SELECT Id, Name, Version_Number__c,  Type__c, Release_Notes__c, Password__c, Version_URL__c FROM Product_Version__c WHERE Product__c = :productId];
        result.totalRecords = result.versions.size();
        return result;
    }
}